package iudx.data.marketplace.authenticator;

import io.vertx.codegen.annotations.Fluent;
import io.vertx.codegen.annotations.GenIgnore;
import io.vertx.codegen.annotations.ProxyGen;
import io.vertx.codegen.annotations.VertxGen;
import io.vertx.core.AsyncResult;
import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import iudx.data.marketplace.authenticator.model.JwtData;

/**
 * The Authentication Service.
 *
 * <h1>Authentication Service</h1>
 *
 * <p>The Authentication Service in the IUDX Data Marketplace defines the operations to be performed
 * with the IUDX Authentication and Authorization server.
 *
 * @see io.vertx.codegen.annotations.ProxyGen
 * @see io.vertx.codegen.annotations.VertxGen
 * @version 1.0
 * @since 2022-08-23
 */
@VertxGen
@ProxyGen
public interface AuthenticationService {

  /**
   * The createProxy helps the code generation blocks to generate proxy code.
   *
   * @param vertx which is the vertx instance
   * @param address which is the proxy address
   * @return AuthenticationServiceVertxEBProxy which is a service proxy
   */
  @GenIgnore
  static AuthenticationService createProxy(Vertx vertx, String address) {
    return new AuthenticationServiceVertxEBProxy(vertx, address);
  }

  /**
   * The tokenIntrospect method implements the authentication and authorization module using IUDX
   * APIs.
   *
   * @param request which is a JsonObject
   * @param authenticationInfo which is a JsonObject
   * @return Future of JsonObject containing information from the decoded token
   */
  Future<JwtData> tokenIntrospect(JsonObject authenticationInfo);

  /**
   * Token introspection for verify endpoint that uses a bearer token generated by DX Auth Server
   *
   * @param authInfo contains Api Endpoint, Header token and Api Method
   * @return Future of Void
   */
  Future<Void> tokenIntrospect4Verify(
      JsonObject authInfo);
}
